---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: governance-policy-propagator-global
subjects:
- kind: ServiceAccount
  name: governance-policy-propagator
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: governance-policy-propagator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: governance-policy-propagator-leader-election-rolebinding
subjects:
- kind: ServiceAccount
  name: governance-policy-propagator
  namespace: open-cluster-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: governance-policy-propagator-leader-election-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: governance-policy-propagator
  namespace: open-cluster-management
